#b#cff0099ff* Participation#nb#nc
* Application Time: Sunday 00:00 to Saturday 12:00
* Combat Place : Server Channel 1
* Conditions
 - Guild Leader
 - Required Guild Level: Level 20+
 - Required Guild Member Level: 30+ 
 - Guild Leader or Kingpin must join.
 -The 8 highest paying guilds will be granted entry to the Guild Siege. 
* Schedule
 - 13:30  Applications Accepted
 - 13:10  Application period Ends.
 - 13:15  Combat begins
 - 13:45  Combat ends.
#b#cffff0000* Guild Siege will only begin if 3 or more Guilds are accepted.#nb#nc